import type { Metadata } from "next";
import "./globals.css";
import AiIconWrapper from "@/components/AiIconWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
        <AiIconWrapper />
      </body>
    </html>
  );
}
